import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface CvPdfSection {
  title: string;
  type: string;
  content: Record<string, unknown> | undefined;
}

export interface CvPdfData {
  cvTitle: string;
  template: string;
  fullName: string;
  professionalHeadline: string | null;
  contactLine: string | null;
  sections: CvPdfSection[];
  generatedAt: Date;
}

/** Renders arbitrary candidate-authored JSON safely as PDF text; never `[object Object]`. */
function toDisplayString(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  try {
    return JSON.stringify(value);
  } catch {
    return '';
  }
}

const DEFAULT_ACCENT = '#1a365d';
const TEMPLATE_ACCENTS: Record<string, string> = {
  MODERN: '#2b6cb0',
  CLASSIC: '#2d3748',
  MINIMAL: '#4a5568',
  ATS_OPTIMIZED: DEFAULT_ACCENT,
};

@Injectable()
export class CvPdfService {
  generate(data: CvPdfData): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const accent = TEMPLATE_ACCENTS[data.template] ?? DEFAULT_ACCENT;
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 55, right: 55 },
        info: { Title: data.cvTitle, Author: 'NextHire', Subject: 'Candidate CV' },
      });

      const buffers: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      doc.rect(0, 0, doc.page.width, 6).fill(accent);

      doc.fontSize(22).font('Helvetica-Bold').fillColor('#1a202c').text(data.fullName, 55, 30);

      if (data.professionalHeadline) {
        doc.moveDown(0.2);
        doc.fontSize(12).font('Helvetica').fillColor('#4a5568').text(data.professionalHeadline);
      }
      if (data.contactLine) {
        doc.moveDown(0.1);
        doc.fontSize(9).font('Helvetica').fillColor('#718096').text(data.contactLine);
      }

      doc.moveDown(0.8);
      doc
        .moveTo(55, doc.y)
        .lineTo(doc.page.width - 55, doc.y)
        .stroke(accent);
      doc.moveDown(0.8);

      for (const section of data.sections) {
        if (!section.content || Object.keys(section.content).length === 0) {
          continue;
        }
        this.renderSection(doc, section, accent);
      }

      doc
        .fontSize(7)
        .font('Helvetica-Oblique')
        .fillColor('#a0aec0')
        .text(
          `Generated by NextHire on ${data.generatedAt.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}`,
          55,
          doc.page.height - 40,
          { align: 'center', width: doc.page.width - 110 },
        );

      doc.end();
    });
  }

  private renderSection(doc: PDFKit.PDFDocument, section: CvPdfSection, accent: string): void {
    if (doc.y > doc.page.height - 120) {
      doc.addPage();
    }

    doc.fontSize(12).font('Helvetica-Bold').fillColor(accent).text(section.title.toUpperCase());
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#2d3748');

    const content = section.content!;

    if (section.type === 'professional_summary') {
      this.writeParagraph(doc, toDisplayString(content.summary));
    } else if (section.type === 'skills') {
      const skills = Array.isArray(content.items) ? (content.items as unknown[]) : [];
      const text = skills
        .map((s) => {
          if (typeof s === 'string') return s;
          const skill = s as Record<string, unknown>;
          const level = toDisplayString(skill.level);
          return `${toDisplayString(skill.name)}${level ? ` (${level})` : ''}`;
        })
        .join('  •  ');
      this.writeParagraph(doc, text);
    } else if (Array.isArray(content.items)) {
      for (const item of content.items as Record<string, unknown>[]) {
        this.renderEntry(doc, section.type, item);
      }
    } else {
      this.writeParagraph(doc, JSON.stringify(content));
    }

    doc.moveDown(0.6);
  }

  private field(item: Record<string, unknown>, key: string): string {
    return toDisplayString(item[key]);
  }

  private renderEntry(doc: PDFKit.PDFDocument, type: string, item: Record<string, unknown>): void {
    if (doc.y > doc.page.height - 90) {
      doc.addPage();
    }

    const f = (key: string) => this.field(item, key);
    let heading = '';
    let subheading = '';
    let body = '';

    switch (type) {
      case 'education':
        heading = f('institutionName');
        subheading = `${f('qualification')}${f('fieldOfStudy') ? ` — ${f('fieldOfStudy')}` : ''}`;
        body = f('description');
        break;
      case 'work_experience':
        heading = `${f('jobTitle')} — ${f('companyName')}`;
        subheading = f('location');
        body = [f('responsibilities'), f('achievements')].filter(Boolean).join('\n');
        break;
      case 'projects':
        heading = f('title');
        subheading = f('roleInProject');
        body = f('summary');
        break;
      case 'certifications':
        heading = f('name');
        subheading = f('issuer');
        body = '';
        break;
      case 'languages':
        heading = f('name');
        subheading = `Speaking: ${f('speaking')} · Reading: ${f('reading')} · Writing: ${f('writing')}`;
        body = '';
        break;
      case 'achievements':
        heading = f('title');
        subheading = f('issuer');
        body = f('description');
        break;
      default:
        heading = f('title') || f('name');
    }

    if (heading) {
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#1a202c').text(heading);
    }
    if (subheading) {
      doc.font('Helvetica').fontSize(9).fillColor('#718096').text(subheading);
    }
    if (body) {
      doc.font('Helvetica').fontSize(9).fillColor('#4a5568');
      this.writeParagraph(doc, body);
    }
    doc.moveDown(0.4);
  }

  private writeParagraph(doc: PDFKit.PDFDocument, text: string): void {
    if (!text) return;
    doc.text(text, { width: doc.page.width - 110, align: 'left' });
  }
}
