export const ASSESSMENT_ERROR_CODES = {
  ASSESSMENT_CATALOG_QUERY_INVALID: 'ASSESSMENT_CATALOG_QUERY_INVALID',
  ASSESSMENT_NOT_FOUND: 'ASSESSMENT_NOT_FOUND',
  ASSESSMENT_CATEGORY_INACTIVE: 'ASSESSMENT_CATEGORY_INACTIVE',
  ASSESSMENT_INVALID_TRANSITION: 'ASSESSMENT_INVALID_TRANSITION',
} as const;
