export const MFA_ERROR_CODES = {
  ENROLLMENT_VALIDATION_FAILED: 'MFA_ENROLLMENT_VALIDATION_FAILED',
  CODE_INVALID: 'MFA_CODE_INVALID',
  RECOVERY_CODE_INVALID: 'MFA_RECOVERY_CODE_INVALID',
  CHALLENGE_INVALID: 'MFA_CHALLENGE_INVALID',
  CHALLENGE_EXPIRED: 'MFA_CHALLENGE_EXPIRED',
  CHALLENGE_CONSUMED: 'MFA_CHALLENGE_CONSUMED',
  REQUIRED_BY_POLICY: 'MFA_REQUIRED_BY_POLICY',
  ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  ENROLLMENT_NOT_STARTED: 'MFA_ENROLLMENT_NOT_STARTED',
  NOT_ENABLED: 'MFA_NOT_ENABLED',
  RATE_LIMITED: 'MFA_RATE_LIMITED',
} as const;

export const MFA_RECOVERY_CODE_COUNT = 10;
export const MFA_RECOVERY_CODE_LENGTH = 12;
export const MFA_CHALLENGE_TTL_MINUTES = 5;
export const MFA_CHALLENGE_MAX_FAILED_ATTEMPTS = 5;
export const MFA_ENROLLMENT_TTL_MINUTES = 10;
export const MFA_TRUSTED_DEVICE_TTL_DAYS = 30;
export const MFA_TOTP_ISSUER = 'NextHire';
export const MFA_TOTP_DIGITS = 6;
export const MFA_TOTP_PERIOD = 30;
export const MFA_TOTP_ALGORITHM = 'SHA1';
export const MFA_TOTP_WINDOW = 1;
