export const EXPERT_FEEDBACK_LIMITS = {
  SCORE_MIN: 1,
  SCORE_MAX: 5,
  RATING_MIN: 1,
  RATING_MAX: 5,
  STRENGTHS_MAX: 2000,
  IMPROVEMENTS_MAX: 2000,
  NEXT_STEPS_MAX: 2000,
  REVIEW_COMMENT_MAX: 2000,
  HIDDEN_REASON_MAX: 300,
} as const;

export const EXPERT_FEEDBACK_RATE_LIMITS = {
  EVALUATION_SUBMIT_PER_HOUR: 20,
  REVIEW_SUBMIT_PER_HOUR: 20,
  MODERATION_ACTION_PER_HOUR: 60,
} as const;

export const EXPERT_FEEDBACK_ERROR_CODES = {
  VALIDATION_FAILED: 'EXPERT_FEEDBACK_VALIDATION_FAILED',
  BOOKING_NOT_FOUND: 'EXPERT_FEEDBACK_BOOKING_NOT_FOUND',
  BOOKING_NOT_COMPLETED: 'EXPERT_FEEDBACK_BOOKING_NOT_COMPLETED',
  ALREADY_SUBMITTED: 'EXPERT_FEEDBACK_ALREADY_SUBMITTED',
  NOT_FOUND: 'EXPERT_FEEDBACK_NOT_FOUND',
  RATE_LIMITED: 'EXPERT_FEEDBACK_RATE_LIMITED',
} as const;
