export const EXPERT_ERROR_CODES = {
  PROFILE_VALIDATION_FAILED: 'EXPERT_PROFILE_VALIDATION_FAILED',
  APPLICATION_NOT_READY: 'EXPERT_APPLICATION_NOT_READY',
  APPLICATION_TRANSITION_INVALID: 'EXPERT_APPLICATION_TRANSITION_INVALID',
  VERIFICATION_DOCUMENT_INVALID: 'EXPERT_VERIFICATION_DOCUMENT_INVALID',
  REVIEW_DECISION_INVALID: 'EXPERT_REVIEW_DECISION_INVALID',
  APPLICATION_REVIEW_PERMISSION_REQUIRED: 'EXPERT_APPLICATION_REVIEW_PERMISSION_REQUIRED',
  APPLICATION_ACCESS_DENIED: 'EXPERT_APPLICATION_ACCESS_DENIED',
  PROFILE_NOT_FOUND: 'EXPERT_PROFILE_NOT_FOUND',
  APPLICATION_NOT_FOUND: 'EXPERT_APPLICATION_NOT_FOUND',
  VERIFICATION_DOCUMENT_NOT_FOUND: 'EXPERT_VERIFICATION_DOCUMENT_NOT_FOUND',
  APPLICATION_ALREADY_ACTIVE: 'EXPERT_APPLICATION_ALREADY_ACTIVE',
  APPLICATION_ALREADY_APPROVED: 'EXPERT_APPLICATION_ALREADY_APPROVED',
  ROLE_ALREADY_ASSIGNED: 'EXPERT_ROLE_ALREADY_ASSIGNED',
  VERIFICATION_DOCUMENT_TOO_LARGE: 'EXPERT_VERIFICATION_DOCUMENT_TOO_LARGE',
  VERIFICATION_DOCUMENT_TYPE_UNSUPPORTED: 'EXPERT_VERIFICATION_DOCUMENT_TYPE_UNSUPPORTED',
  APPLICATION_RATE_LIMITED: 'EXPERT_APPLICATION_RATE_LIMITED',
} as const;

export const EXPERT_LIMITS = {
  MIN_PROFESSIONAL_TITLE: 3,
  MAX_PROFESSIONAL_TITLE: 150,
  MIN_PROFESSIONAL_SUMMARY: 100,
  MAX_PROFESSIONAL_SUMMARY: 3000,
  MIN_YEARS_EXPERIENCE: 1,
  MAX_YEARS_EXPERIENCE: 60,
  MAX_CURRENT_COMPANY: 150,
  MAX_CURRENT_POSITION: 150,
  MAX_HIGHEST_EDUCATION: 200,
  MAX_URL: 500,
  MIN_INTERVIEW_LANGUAGES: 1,
  MAX_INTERVIEW_LANGUAGES: 10,
  MAX_CITY: 120,
  MAX_DOCUMENTS: 10,
  MAX_DOCUMENT_SIZE_MB: 10,
  MAX_DOCUMENT_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_REVIEW_NOTE: 2000,
  MAX_APPLICANT_RESPONSE: 2000,
} as const;

export const EXPERT_DOCUMENT_TYPES = [
  'GOVERNMENT_ID',
  'PROFESSIONAL_CERTIFICATE',
  'EMPLOYMENT_PROOF',
  'EDUCATION_CERTIFICATE',
  'OTHER_SUPPORTING_DOCUMENT',
] as const;

export const EXPERT_ALLOWED_MIME_TYPES = ['application/pdf', 'image/jpeg', 'image/png'] as const;

export const EXPERT_ALLOWED_EXTENSIONS = ['.pdf', '.jpg', '.jpeg', '.png'] as const;

export const EXPERT_APPLICATION_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'UNDER_REVIEW',
  'CHANGES_REQUESTED',
  'APPROVED',
  'REJECTED',
  'WITHDRAWN',
] as const;

export const EXPERT_REJECTION_REASONS = [
  'INSUFFICIENT_EXPERIENCE',
  'INVALID_CREDENTIALS',
  'DOCUMENT_QUALITY',
  'COMPLIANCE_ISSUE',
  'OTHER',
] as const;

export const EXPERT_RATE_LIMITS = {
  PROFILE_UPDATE_PER_HOUR: 30,
  APPLICATION_SUBMIT_PER_DAY: 5,
  DOCUMENT_UPLOAD_PER_HOUR: 20,
  DOCUMENT_ACCESS_PER_HOUR: 30,
  REVIEW_DECISION_PER_HOUR: 30,
} as const;
