export const EXPERT_PAYOUT_ACCOUNT_TYPES = ['bank_account', 'paypal'] as const;

export const EXPERT_WALLET_STATUSES = ['ACTIVE', 'SUSPENDED', 'CLOSED'] as const;

export const EXPERT_PAYOUT_STATUSES = [
  'PENDING',
  'PROCESSING',
  'COMPLETED',
  'FAILED',
  'CANCELLED',
] as const;

/** Platform commission taken from each completed session, shown to experts as a forward-looking
 * earnings estimate. Not applied anywhere yet — no real payment capture exists (NH-M29). */
export const EXPERT_PLATFORM_COMMISSION_RATE = 0.2;

export const EXPERT_WALLET_LIMITS = {
  ACCOUNT_HOLDER_MAX: 200,
  ACCOUNT_NUMBER_MIN: 4,
  ACCOUNT_NUMBER_MAX: 34,
  ROUTING_NUMBER_MAX: 50,
  PAYOUT_AMOUNT_MIN: '1.00',
} as const;

export const EXPERT_WALLET_RATE_LIMITS = {
  PAYOUT_ACCOUNT_CREATE_PER_HOUR: 10,
  PAYOUT_REQUEST_PER_HOUR: 10,
} as const;

export const EXPERT_WALLET_ERROR_CODES = {
  VALIDATION_FAILED: 'EXPERT_WALLET_VALIDATION_FAILED',
  ALREADY_INITIALIZED: 'EXPERT_WALLET_ALREADY_INITIALIZED',
  NOT_FOUND: 'EXPERT_WALLET_NOT_FOUND',
  PAYOUT_ACCOUNT_NOT_FOUND: 'EXPERT_WALLET_PAYOUT_ACCOUNT_NOT_FOUND',
  PAYOUT_ACCOUNT_NOT_VERIFIED: 'EXPERT_WALLET_PAYOUT_ACCOUNT_NOT_VERIFIED',
  INSUFFICIENT_BALANCE: 'EXPERT_WALLET_INSUFFICIENT_BALANCE',
  RATE_LIMITED: 'EXPERT_WALLET_RATE_LIMITED',
} as const;
