export const COMPANY_ERROR_CODES = {
  PROFILE_VALIDATION_FAILED: 'COMPANY_PROFILE_VALIDATION_FAILED',
  PROFILE_NOT_FOUND: 'COMPANY_PROFILE_NOT_FOUND',
  APPLICATION_NOT_FOUND: 'COMPANY_APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_ACTIVE: 'COMPANY_APPLICATION_ALREADY_ACTIVE',
  APPLICATION_ALREADY_APPROVED: 'COMPANY_APPLICATION_ALREADY_APPROVED',
  APPLICATION_NOT_READY: 'COMPANY_APPLICATION_NOT_READY',
  APPLICATION_TRANSITION_INVALID: 'COMPANY_APPLICATION_TRANSITION_INVALID',
  REVIEW_DECISION_INVALID: 'COMPANY_REVIEW_DECISION_INVALID',
  VERIFICATION_DOCUMENT_INVALID: 'COMPANY_VERIFICATION_DOCUMENT_INVALID',
  VERIFICATION_DOCUMENT_NOT_FOUND: 'COMPANY_VERIFICATION_DOCUMENT_NOT_FOUND',
  VERIFICATION_DOCUMENT_TOO_LARGE: 'COMPANY_VERIFICATION_DOCUMENT_TOO_LARGE',
  VERIFICATION_DOCUMENT_TYPE_UNSUPPORTED: 'COMPANY_VERIFICATION_DOCUMENT_TYPE_UNSUPPORTED',
  NOT_A_MEMBER: 'COMPANY_NOT_A_MEMBER',
  INSUFFICIENT_ROLE: 'COMPANY_INSUFFICIENT_ROLE',
  MEMBER_NOT_FOUND: 'COMPANY_MEMBER_NOT_FOUND',
  CANNOT_MANAGE_OWNER: 'COMPANY_CANNOT_MANAGE_OWNER',
  CANNOT_ASSIGN_OWNER_ROLE: 'COMPANY_CANNOT_ASSIGN_OWNER_ROLE',
  CANNOT_REMOVE_SELF: 'COMPANY_CANNOT_REMOVE_SELF',
  INVITEE_NOT_FOUND: 'COMPANY_INVITEE_NOT_FOUND',
  INVITEE_ALREADY_MEMBER: 'COMPANY_INVITEE_ALREADY_MEMBER',
  INVITATION_ALREADY_PENDING: 'COMPANY_INVITATION_ALREADY_PENDING',
  INVITATION_NOT_FOUND: 'COMPANY_INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'COMPANY_INVITATION_EXPIRED',
  INVITATION_NOT_PENDING: 'COMPANY_INVITATION_NOT_PENDING',
  INVITATION_EMAIL_MISMATCH: 'COMPANY_INVITATION_EMAIL_MISMATCH',
} as const;

export const COMPANY_LIMITS = {
  MIN_NAME: 2,
  MAX_NAME: 200,
  MAX_LEGAL_NAME: 200,
  MAX_WEBSITE: 500,
  MAX_INDUSTRY: 150,
  MIN_DESCRIPTION: 50,
  MAX_DESCRIPTION: 3000,
  MAX_CITY: 120,
  MAX_DOCUMENTS: 10,
  MAX_DOCUMENT_SIZE_MB: 10,
  MAX_DOCUMENT_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_REVIEW_NOTE: 2000,
  MAX_APPLICANT_RESPONSE: 2000,
} as const;

export const COMPANY_SIZES = ['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+'] as const;

export const COMPANY_DOCUMENT_TYPES = [
  'BUSINESS_REGISTRATION',
  'TAX_CERTIFICATE',
  'AUTHORIZATION_LETTER',
  'OTHER_SUPPORTING_DOCUMENT',
] as const;

export const COMPANY_ALLOWED_MIME_TYPES = ['application/pdf', 'image/jpeg', 'image/png'] as const;

export const COMPANY_VERIFICATION_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'UNDER_REVIEW',
  'CHANGES_REQUESTED',
  'APPROVED',
  'REJECTED',
  'WITHDRAWN',
] as const;

export const COMPANY_REJECTION_REASONS = [
  'INVALID_DOCUMENTS',
  'UNVERIFIABLE_BUSINESS',
  'DOCUMENT_QUALITY',
  'COMPLIANCE_ISSUE',
  'OTHER',
] as const;

export const COMPANY_RATE_LIMITS = {
  PROFILE_UPDATE_PER_HOUR: 30,
  APPLICATION_SUBMIT_PER_DAY: 5,
  DOCUMENT_UPLOAD_PER_HOUR: 20,
  DOCUMENT_ACCESS_PER_HOUR: 30,
  REVIEW_DECISION_PER_HOUR: 30,
  INVITATION_SEND_PER_DAY: 20,
  INVITATION_ACTION_PER_HOUR: 30,
} as const;

export const COMPANY_MEMBER_ROLES = ['OWNER', 'ADMIN', 'RECRUITER', 'VIEWER'] as const;

export const COMPANY_INVITABLE_ROLES = ['ADMIN', 'RECRUITER', 'VIEWER'] as const;

export const COMPANY_INVITATION_STATUSES = [
  'PENDING',
  'ACCEPTED',
  'DECLINED',
  'REVOKED',
  'EXPIRED',
] as const;

export const COMPANY_INVITATION_EXPIRY_DAYS = 7;
