export const TALENT_PIPELINE_STAGES = [
  'SHORTLISTED',
  'CONTACTED',
  'SCREENING',
  'INTERVIEWING',
  'OFFER',
  'HIRED',
  'REJECTED',
] as const;

export const TALENT_SHORTLIST_LIMITS = {
  MIN_NAME: 2,
  MAX_NAME: 150,
  MAX_DESCRIPTION: 1000,
  MAX_NOTES: 2000,
  MAX_TAGS: 15,
  MAX_TAG_LENGTH: 40,
} as const;

export const TALENT_PIPELINE_RATE_LIMITS = {
  SHORTLIST_WRITE_PER_HOUR: 60,
  MEMBER_WRITE_PER_HOUR: 120,
} as const;

export const TALENT_PIPELINE_ERROR_CODES = {
  SHORTLIST_NOT_FOUND: 'TALENT_SHORTLIST_NOT_FOUND',
  SHORTLIST_VALIDATION_FAILED: 'TALENT_SHORTLIST_VALIDATION_FAILED',
  MEMBER_NOT_FOUND: 'TALENT_SHORTLIST_MEMBER_NOT_FOUND',
  MEMBER_ALREADY_ADDED: 'TALENT_SHORTLIST_MEMBER_ALREADY_ADDED',
  CANDIDATE_NOT_DISCOVERABLE: 'TALENT_CANDIDATE_NOT_DISCOVERABLE',
  READ_ONLY_ROLE: 'TALENT_PIPELINE_READ_ONLY_ROLE',
} as const;
